// Code generated by protoc-gen-go.
// source: rpc.proto
// DO NOT EDIT!

/*
Package rpc is a generated protocol buffer package.

It is generated from these files:
	rpc.proto

It has these top-level messages:
	CreateAccountRequest
	CreateAccountResponse
	UpdateAccountRequest
	UpdateAccountResponse
	CreateCertificateRequest
	CreateCertificateResponse
	ResolveChallengeRequest
	ResolveChallengeResponse
	CertificateStateRequest
	CertificateStateResponse
	GetCertificateRequest
	GetCertificateResponse
*/
package rpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AccountEnvironment int32

const (
	AccountEnvironment_PRODUCTION AccountEnvironment = 0
	AccountEnvironment_STAGING    AccountEnvironment = 1
)

var AccountEnvironment_name = map[int32]string{
	0: "PRODUCTION",
	1: "STAGING",
}
var AccountEnvironment_value = map[string]int32{
	"PRODUCTION": 0,
	"STAGING":    1,
}

func (x AccountEnvironment) String() string {
	return proto.EnumName(AccountEnvironment_name, int32(x))
}
func (AccountEnvironment) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type CreateAccountRequest struct {
	Owner       string             `protobuf:"bytes,1,opt,name=owner" json:"owner,omitempty"`
	Key         string             `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
	Environment AccountEnvironment `protobuf:"varint,3,opt,name=environment,enum=rpc.AccountEnvironment" json:"environment,omitempty"`
}

func (m *CreateAccountRequest) Reset()                    { *m = CreateAccountRequest{} }
func (m *CreateAccountRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateAccountRequest) ProtoMessage()               {}
func (*CreateAccountRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CreateAccountRequest) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *CreateAccountRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *CreateAccountRequest) GetEnvironment() AccountEnvironment {
	if m != nil {
		return m.Environment
	}
	return AccountEnvironment_PRODUCTION
}

type CreateAccountResponse struct {
	Id    string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Token string `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
}

func (m *CreateAccountResponse) Reset()                    { *m = CreateAccountResponse{} }
func (m *CreateAccountResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateAccountResponse) ProtoMessage()               {}
func (*CreateAccountResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateAccountResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreateAccountResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type UpdateAccountRequest struct {
	Id          string             `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Environment AccountEnvironment `protobuf:"varint,2,opt,name=environment,enum=rpc.AccountEnvironment" json:"environment,omitempty"`
}

func (m *UpdateAccountRequest) Reset()                    { *m = UpdateAccountRequest{} }
func (m *UpdateAccountRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateAccountRequest) ProtoMessage()               {}
func (*UpdateAccountRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *UpdateAccountRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateAccountRequest) GetEnvironment() AccountEnvironment {
	if m != nil {
		return m.Environment
	}
	return AccountEnvironment_PRODUCTION
}

type UpdateAccountResponse struct {
}

func (m *UpdateAccountResponse) Reset()                    { *m = UpdateAccountResponse{} }
func (m *UpdateAccountResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateAccountResponse) ProtoMessage()               {}
func (*UpdateAccountResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type CreateCertificateRequest struct {
	AccountID     string `protobuf:"bytes,1,opt,name=accountID" json:"accountID,omitempty"`
	AccountToken  string `protobuf:"bytes,2,opt,name=accountToken" json:"accountToken,omitempty"`
	Domain        string `protobuf:"bytes,3,opt,name=domain" json:"domain,omitempty"`
	ChallengeType string `protobuf:"bytes,4,opt,name=challengeType" json:"challengeType,omitempty"`
}

func (m *CreateCertificateRequest) Reset()                    { *m = CreateCertificateRequest{} }
func (m *CreateCertificateRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateCertificateRequest) ProtoMessage()               {}
func (*CreateCertificateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *CreateCertificateRequest) GetAccountID() string {
	if m != nil {
		return m.AccountID
	}
	return ""
}

func (m *CreateCertificateRequest) GetAccountToken() string {
	if m != nil {
		return m.AccountToken
	}
	return ""
}

func (m *CreateCertificateRequest) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *CreateCertificateRequest) GetChallengeType() string {
	if m != nil {
		return m.ChallengeType
	}
	return ""
}

type CreateCertificateResponse struct {
	AccountID string `protobuf:"bytes,1,opt,name=accountID" json:"accountID,omitempty"`
	DomainID  string `protobuf:"bytes,2,opt,name=domainID" json:"domainID,omitempty"`
	State     string `protobuf:"bytes,3,opt,name=state" json:"state,omitempty"`
}

func (m *CreateCertificateResponse) Reset()                    { *m = CreateCertificateResponse{} }
func (m *CreateCertificateResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateCertificateResponse) ProtoMessage()               {}
func (*CreateCertificateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *CreateCertificateResponse) GetAccountID() string {
	if m != nil {
		return m.AccountID
	}
	return ""
}

func (m *CreateCertificateResponse) GetDomainID() string {
	if m != nil {
		return m.DomainID
	}
	return ""
}

func (m *CreateCertificateResponse) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

type ResolveChallengeRequest struct {
	AccountID    string `protobuf:"bytes,1,opt,name=accountID" json:"accountID,omitempty"`
	AccountToken string `protobuf:"bytes,2,opt,name=accountToken" json:"accountToken,omitempty"`
	Domain       string `protobuf:"bytes,3,opt,name=domain" json:"domain,omitempty"`
}

func (m *ResolveChallengeRequest) Reset()                    { *m = ResolveChallengeRequest{} }
func (m *ResolveChallengeRequest) String() string            { return proto.CompactTextString(m) }
func (*ResolveChallengeRequest) ProtoMessage()               {}
func (*ResolveChallengeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ResolveChallengeRequest) GetAccountID() string {
	if m != nil {
		return m.AccountID
	}
	return ""
}

func (m *ResolveChallengeRequest) GetAccountToken() string {
	if m != nil {
		return m.AccountToken
	}
	return ""
}

func (m *ResolveChallengeRequest) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

type ResolveChallengeResponse struct {
	Certificate string `protobuf:"bytes,1,opt,name=certificate" json:"certificate,omitempty"`
	Key         string `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
	Chain       string `protobuf:"bytes,3,opt,name=chain" json:"chain,omitempty"`
}

func (m *ResolveChallengeResponse) Reset()                    { *m = ResolveChallengeResponse{} }
func (m *ResolveChallengeResponse) String() string            { return proto.CompactTextString(m) }
func (*ResolveChallengeResponse) ProtoMessage()               {}
func (*ResolveChallengeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *ResolveChallengeResponse) GetCertificate() string {
	if m != nil {
		return m.Certificate
	}
	return ""
}

func (m *ResolveChallengeResponse) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ResolveChallengeResponse) GetChain() string {
	if m != nil {
		return m.Chain
	}
	return ""
}

type CertificateStateRequest struct {
	AccountID    string `protobuf:"bytes,1,opt,name=accountID" json:"accountID,omitempty"`
	AccountToken string `protobuf:"bytes,2,opt,name=accountToken" json:"accountToken,omitempty"`
	DomainID     string `protobuf:"bytes,3,opt,name=domainID" json:"domainID,omitempty"`
}

func (m *CertificateStateRequest) Reset()                    { *m = CertificateStateRequest{} }
func (m *CertificateStateRequest) String() string            { return proto.CompactTextString(m) }
func (*CertificateStateRequest) ProtoMessage()               {}
func (*CertificateStateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *CertificateStateRequest) GetAccountID() string {
	if m != nil {
		return m.AccountID
	}
	return ""
}

func (m *CertificateStateRequest) GetAccountToken() string {
	if m != nil {
		return m.AccountToken
	}
	return ""
}

func (m *CertificateStateRequest) GetDomainID() string {
	if m != nil {
		return m.DomainID
	}
	return ""
}

type CertificateStateResponse struct {
}

func (m *CertificateStateResponse) Reset()                    { *m = CertificateStateResponse{} }
func (m *CertificateStateResponse) String() string            { return proto.CompactTextString(m) }
func (*CertificateStateResponse) ProtoMessage()               {}
func (*CertificateStateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type GetCertificateRequest struct {
	AccountID    string `protobuf:"bytes,1,opt,name=accountID" json:"accountID,omitempty"`
	AccountToken string `protobuf:"bytes,2,opt,name=accountToken" json:"accountToken,omitempty"`
	Domain       string `protobuf:"bytes,3,opt,name=domain" json:"domain,omitempty"`
}

func (m *GetCertificateRequest) Reset()                    { *m = GetCertificateRequest{} }
func (m *GetCertificateRequest) String() string            { return proto.CompactTextString(m) }
func (*GetCertificateRequest) ProtoMessage()               {}
func (*GetCertificateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *GetCertificateRequest) GetAccountID() string {
	if m != nil {
		return m.AccountID
	}
	return ""
}

func (m *GetCertificateRequest) GetAccountToken() string {
	if m != nil {
		return m.AccountToken
	}
	return ""
}

func (m *GetCertificateRequest) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

type GetCertificateResponse struct {
	Certificate string `protobuf:"bytes,1,opt,name=certificate" json:"certificate,omitempty"`
	Key         string `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
	Chain       string `protobuf:"bytes,3,opt,name=chain" json:"chain,omitempty"`
}

func (m *GetCertificateResponse) Reset()                    { *m = GetCertificateResponse{} }
func (m *GetCertificateResponse) String() string            { return proto.CompactTextString(m) }
func (*GetCertificateResponse) ProtoMessage()               {}
func (*GetCertificateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *GetCertificateResponse) GetCertificate() string {
	if m != nil {
		return m.Certificate
	}
	return ""
}

func (m *GetCertificateResponse) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *GetCertificateResponse) GetChain() string {
	if m != nil {
		return m.Chain
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateAccountRequest)(nil), "rpc.CreateAccountRequest")
	proto.RegisterType((*CreateAccountResponse)(nil), "rpc.CreateAccountResponse")
	proto.RegisterType((*UpdateAccountRequest)(nil), "rpc.UpdateAccountRequest")
	proto.RegisterType((*UpdateAccountResponse)(nil), "rpc.UpdateAccountResponse")
	proto.RegisterType((*CreateCertificateRequest)(nil), "rpc.CreateCertificateRequest")
	proto.RegisterType((*CreateCertificateResponse)(nil), "rpc.CreateCertificateResponse")
	proto.RegisterType((*ResolveChallengeRequest)(nil), "rpc.ResolveChallengeRequest")
	proto.RegisterType((*ResolveChallengeResponse)(nil), "rpc.ResolveChallengeResponse")
	proto.RegisterType((*CertificateStateRequest)(nil), "rpc.CertificateStateRequest")
	proto.RegisterType((*CertificateStateResponse)(nil), "rpc.CertificateStateResponse")
	proto.RegisterType((*GetCertificateRequest)(nil), "rpc.GetCertificateRequest")
	proto.RegisterType((*GetCertificateResponse)(nil), "rpc.GetCertificateResponse")
	proto.RegisterEnum("rpc.AccountEnvironment", AccountEnvironment_name, AccountEnvironment_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for API service

type APIClient interface {
	CreateAccount(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*CreateAccountResponse, error)
	UpdateAccount(ctx context.Context, in *UpdateAccountRequest, opts ...grpc.CallOption) (*UpdateAccountResponse, error)
	CreateCertificate(ctx context.Context, in *CreateCertificateRequest, opts ...grpc.CallOption) (*CreateCertificateResponse, error)
	ResolveCertificateChallenge(ctx context.Context, in *ResolveChallengeRequest, opts ...grpc.CallOption) (*ResolveChallengeResponse, error)
	CheckCertificateState(ctx context.Context, in *CertificateStateRequest, opts ...grpc.CallOption) (*CertificateStateResponse, error)
	GetCertificate(ctx context.Context, in *GetCertificateRequest, opts ...grpc.CallOption) (*GetCertificateResponse, error)
}

type aPIClient struct {
	cc *grpc.ClientConn
}

func NewAPIClient(cc *grpc.ClientConn) APIClient {
	return &aPIClient{cc}
}

func (c *aPIClient) CreateAccount(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*CreateAccountResponse, error) {
	out := new(CreateAccountResponse)
	err := grpc.Invoke(ctx, "/rpc.API/CreateAccount", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) UpdateAccount(ctx context.Context, in *UpdateAccountRequest, opts ...grpc.CallOption) (*UpdateAccountResponse, error) {
	out := new(UpdateAccountResponse)
	err := grpc.Invoke(ctx, "/rpc.API/UpdateAccount", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) CreateCertificate(ctx context.Context, in *CreateCertificateRequest, opts ...grpc.CallOption) (*CreateCertificateResponse, error) {
	out := new(CreateCertificateResponse)
	err := grpc.Invoke(ctx, "/rpc.API/CreateCertificate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) ResolveCertificateChallenge(ctx context.Context, in *ResolveChallengeRequest, opts ...grpc.CallOption) (*ResolveChallengeResponse, error) {
	out := new(ResolveChallengeResponse)
	err := grpc.Invoke(ctx, "/rpc.API/ResolveCertificateChallenge", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) CheckCertificateState(ctx context.Context, in *CertificateStateRequest, opts ...grpc.CallOption) (*CertificateStateResponse, error) {
	out := new(CertificateStateResponse)
	err := grpc.Invoke(ctx, "/rpc.API/CheckCertificateState", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) GetCertificate(ctx context.Context, in *GetCertificateRequest, opts ...grpc.CallOption) (*GetCertificateResponse, error) {
	out := new(GetCertificateResponse)
	err := grpc.Invoke(ctx, "/rpc.API/GetCertificate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for API service

type APIServer interface {
	CreateAccount(context.Context, *CreateAccountRequest) (*CreateAccountResponse, error)
	UpdateAccount(context.Context, *UpdateAccountRequest) (*UpdateAccountResponse, error)
	CreateCertificate(context.Context, *CreateCertificateRequest) (*CreateCertificateResponse, error)
	ResolveCertificateChallenge(context.Context, *ResolveChallengeRequest) (*ResolveChallengeResponse, error)
	CheckCertificateState(context.Context, *CertificateStateRequest) (*CertificateStateResponse, error)
	GetCertificate(context.Context, *GetCertificateRequest) (*GetCertificateResponse, error)
}

func RegisterAPIServer(s *grpc.Server, srv APIServer) {
	s.RegisterService(&_API_serviceDesc, srv)
}

func _API_CreateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).CreateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.API/CreateAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).CreateAccount(ctx, req.(*CreateAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_UpdateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).UpdateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.API/UpdateAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).UpdateAccount(ctx, req.(*UpdateAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_CreateCertificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCertificateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).CreateCertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.API/CreateCertificate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).CreateCertificate(ctx, req.(*CreateCertificateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_ResolveCertificateChallenge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveChallengeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).ResolveCertificateChallenge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.API/ResolveCertificateChallenge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).ResolveCertificateChallenge(ctx, req.(*ResolveChallengeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_CheckCertificateState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CertificateStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).CheckCertificateState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.API/CheckCertificateState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).CheckCertificateState(ctx, req.(*CertificateStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_GetCertificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCertificateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetCertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.API/GetCertificate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetCertificate(ctx, req.(*GetCertificateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _API_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.API",
	HandlerType: (*APIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAccount",
			Handler:    _API_CreateAccount_Handler,
		},
		{
			MethodName: "UpdateAccount",
			Handler:    _API_UpdateAccount_Handler,
		},
		{
			MethodName: "CreateCertificate",
			Handler:    _API_CreateCertificate_Handler,
		},
		{
			MethodName: "ResolveCertificateChallenge",
			Handler:    _API_ResolveCertificateChallenge_Handler,
		},
		{
			MethodName: "CheckCertificateState",
			Handler:    _API_CheckCertificateState_Handler,
		},
		{
			MethodName: "GetCertificate",
			Handler:    _API_GetCertificate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc.proto",
}

func init() { proto.RegisterFile("rpc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 528 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x55, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x25, 0x31, 0x2d, 0x64, 0x42, 0xa2, 0xb0, 0x4a, 0x1a, 0xd7, 0x6d, 0x51, 0xb4, 0xe2, 0x50,
	0x71, 0xa8, 0x44, 0x39, 0x71, 0xe0, 0x10, 0x39, 0x34, 0xf2, 0xa5, 0xad, 0x5c, 0xf7, 0xc2, 0xcd,
	0xb5, 0x07, 0x62, 0x25, 0xf5, 0xba, 0xf6, 0xb6, 0x55, 0xfe, 0x0a, 0x3f, 0x90, 0xdf, 0x81, 0xe2,
	0x9d, 0xd4, 0xdf, 0x48, 0x48, 0x85, 0x5b, 0x66, 0xc6, 0x3b, 0xef, 0xed, 0xdb, 0x37, 0x13, 0xe8,
	0xc4, 0x91, 0x77, 0x12, 0xc5, 0x42, 0x0a, 0xa6, 0xc5, 0x91, 0xc7, 0xd7, 0x30, 0x34, 0x63, 0x74,
	0x25, 0x4e, 0x3d, 0x4f, 0xdc, 0x87, 0xd2, 0xc6, 0xbb, 0x7b, 0x4c, 0x24, 0x1b, 0xc2, 0x8e, 0x78,
	0x0c, 0x31, 0xd6, 0x5b, 0x93, 0xd6, 0x71, 0xc7, 0x56, 0x01, 0x1b, 0x80, 0xb6, 0xc4, 0xb5, 0xde,
	0x4e, 0x73, 0x9b, 0x9f, 0xec, 0x33, 0x74, 0x31, 0x7c, 0x08, 0x62, 0x11, 0xde, 0x62, 0x28, 0x75,
	0x6d, 0xd2, 0x3a, 0xee, 0x9f, 0x8e, 0x4f, 0x36, 0x28, 0xd4, 0xf1, 0x6b, 0x56, 0xb6, 0xf3, 0xdf,
	0xf2, 0x2f, 0x30, 0x2a, 0x41, 0x27, 0x91, 0x08, 0x13, 0x64, 0x7d, 0x68, 0x07, 0x3e, 0x01, 0xb7,
	0x03, 0x7f, 0xc3, 0x45, 0x8a, 0x25, 0x86, 0x84, 0xab, 0x02, 0xee, 0xc2, 0xf0, 0x3a, 0xf2, 0xab,
	0xcc, 0xcb, 0xa7, 0x4b, 0x0c, 0xdb, 0x7f, 0xc1, 0x70, 0x0c, 0xa3, 0x12, 0x84, 0x62, 0xc8, 0x7f,
	0xb6, 0x40, 0x57, 0xdc, 0x4d, 0x8c, 0x65, 0xf0, 0x3d, 0xf0, 0x5c, 0x89, 0x5b, 0x02, 0x87, 0xd0,
	0x71, 0xd5, 0xf7, 0xd6, 0x8c, 0x78, 0x64, 0x09, 0xc6, 0xe1, 0x0d, 0x05, 0x4e, 0xee, 0x4e, 0x85,
	0x1c, 0xdb, 0x83, 0x5d, 0x5f, 0xdc, 0xba, 0x41, 0x98, 0xea, 0xd9, 0xb1, 0x29, 0x62, 0xef, 0xa1,
	0xe7, 0x2d, 0xdc, 0xd5, 0x0a, 0xc3, 0x1f, 0xe8, 0xac, 0x23, 0xd4, 0x5f, 0xa6, 0xe5, 0x62, 0x92,
	0x2f, 0x61, 0xbf, 0x86, 0x1b, 0x69, 0xfb, 0x67, 0x72, 0x06, 0xbc, 0x56, 0x50, 0xd6, 0x8c, 0x88,
	0x3d, 0xc5, 0x9b, 0x57, 0x48, 0xa4, 0x2b, 0x91, 0x38, 0xa9, 0x80, 0x27, 0x30, 0xb6, 0x31, 0x11,
	0xab, 0x07, 0x34, 0xb7, 0x24, 0xfe, 0xb9, 0x0e, 0xdc, 0x07, 0xbd, 0x0a, 0x4a, 0x17, 0x9c, 0x40,
	0xd7, 0xcb, 0xee, 0x4d, 0xb8, 0xf9, 0x54, 0x8d, 0x89, 0x87, 0xb0, 0xe3, 0x2d, 0x32, 0x18, 0x15,
	0xf0, 0x47, 0x18, 0xe7, 0x14, 0xbc, 0x92, 0xcf, 0xfa, 0xc4, 0x79, 0xa5, 0xb5, 0xa2, 0xd2, 0xdc,
	0x00, 0xbd, 0x0a, 0x4c, 0xce, 0xbb, 0x83, 0xd1, 0x1c, 0xe5, 0xff, 0x74, 0x1d, 0xbf, 0x81, 0xbd,
	0x32, 0xe4, 0x73, 0x6b, 0xfd, 0xe1, 0x23, 0xb0, 0xea, 0x30, 0xb2, 0x3e, 0xc0, 0xa5, 0x7d, 0x31,
	0xbb, 0x36, 0x1d, 0xeb, 0xe2, 0x7c, 0xf0, 0x82, 0x75, 0xe1, 0xd5, 0x95, 0x33, 0x9d, 0x5b, 0xe7,
	0xf3, 0x41, 0xeb, 0xf4, 0x97, 0x06, 0xda, 0xf4, 0xd2, 0x62, 0x67, 0xd0, 0x2b, 0xac, 0x11, 0xb6,
	0x9f, 0xce, 0x76, 0xdd, 0x56, 0x33, 0x8c, 0xba, 0x12, 0x5d, 0xe6, 0x0c, 0x7a, 0x85, 0x61, 0xa7,
	0x3e, 0x75, 0x3b, 0x86, 0xfa, 0xd4, 0xee, 0x06, 0x66, 0xc3, 0xdb, 0xca, 0xf8, 0xb1, 0xa3, 0x1c,
	0x70, 0xf5, 0xf1, 0x8c, 0x77, 0x4d, 0x65, 0xea, 0xf9, 0x0d, 0x0e, 0xb6, 0x86, 0xcf, 0xaa, 0x4f,
	0xde, 0x67, 0x87, 0xe9, 0xf1, 0x86, 0x39, 0x34, 0x8e, 0x1a, 0xaa, 0xd4, 0xdb, 0x81, 0x91, 0xb9,
	0x40, 0x6f, 0x59, 0xb6, 0x1c, 0x75, 0x6d, 0x18, 0x01, 0xea, 0xda, 0xe4, 0x53, 0x66, 0x41, 0xbf,
	0x68, 0x1a, 0xa6, 0x34, 0xab, 0x35, 0xaf, 0x71, 0x50, 0x5b, 0x53, 0xad, 0x6e, 0x76, 0xd3, 0xbf,
	0xab, 0x4f, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0xea, 0x1d, 0x8a, 0x6f, 0xbb, 0x06, 0x00, 0x00,
}
